[tool.poetry]
name = "oracle"
version = "0.1.0"
description = ""
authors = ["Yosha87 <contact@yoshachess.com>", "Athroniaeth <pierre.chaumont@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
